# Generated by Django 5.1.4 on 2025-01-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.CharField(default="", max_length=900),
        ),
    ]
