# Generated by Django 5.1.4 on 2025-01-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviesdata",
            name="typ",
            field=models.CharField(default="action", max_length=200),
        ),
    ]
