# Generated by Django 5.1.4 on 2025-01-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_moviesdata_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviesdata",
            name="image",
            field=models.ImageField(
                default="Images/None/noimage.jpg", upload_to="Images/"
            ),
        ),
    ]
